# Generated by Django 3.2 on 2021-07-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('image', models.ImageField(upload_to='Article Images/%Y/%m', verbose_name='image')),
                ('description', models.TextField(max_length=400, verbose_name='description')),
                ('body', models.TextField(max_length=10000, verbose_name='body')),
                ('pubdate', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
